### ISSUE TITLE
Support same concurent action runinng in parallel

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#11]
## Steps

- Open 2 terminal side by side
- cd to any dir where an action is discovered
- exececute that action at the same time, on both terminals

## Observed

- One terminal will run the action as expected
- The other one will fail with erorr : 
```
INFO: Image "platform-actions-compare-artifact:latest" exists locally
Error: Error response from daemon: Conflict. The container name "/plasmactl_platform_compare_artifact" is already in use by container "95ae8a0b1887cdda95077bf7edf3413f852ca4aa14c5e1b2feb2cefb5642828a". You have to remove (or rename) that container to be able to reuse that name.
```

## Expected

- It should be possible to run the same action multiple times at the same time
- Container name could be appended with some unique short sha to make it work

**Comment by iignatevich** [comment]
https://github.com/launchrctl/launchr/pull/13

**Comment by lexbritvin** [comment]
Fixed.
Will be provided in the next release.

**Comment by davidferlay** [comment]
Confirmed working as expected

![image](https://github.com/launchrctl/launchr/assets/20738264/105ab3bb-af87-406e-8721-3552249b3e88)
