### ISSUE TITLE
Ability to use volume from working dir

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#12]
## Context

- `/var/run/docker.sock` is required for plasmactl to run
- Consider cases where docker socket used does not belong to current env :
   - ie in a CI context: where socket is mouted by gitlab-runner from host to CI container, in which plasmactl actions are executed

## Observed

- Plasmactl does not mount current directory (but a path from the host owning the docker socket):
  - Any script executed by action.yaml is not found > action fails
  - Current directory (git repo) brought by CI (to execute action against) is not found > action may fail

## Expected

- Plasmactl could provide the option to mount current directory so that:
  - Any script executed by action.yaml will be found and executed as expected
  - Current directory (git repo) brought by CI will be found

- Option `-m` or `--mount-current-dir` would do these successive action:
  1. Create volume
  2. Copy current dir to it
  3. Excute plasmactl container with volume mounted
  4. Delete volume at the end of plasmactl action (whether it succeeds or fials)

It may be a good thing to bring this with a launchr plugin

**Comment by lexbritvin** [comment]
Implemented `--use-volume-wd` flag, to me, the name better represents the behavior than in the request. 
I didn't make shorthand `-m` as currently it's a bit complex to mix options for actions and other and have no conflicts in definition. We will need to address that later, because we may need aliases for action options also.

The code in the `main` branch, I didn't prepare a release just yet.

**Comment by davidferlay** [comment]
Looking good ! 

Creating release

![image](https://github.com/launchrctl/launchr/assets/20738264/dcd6ae30-db65-4f29-85f1-98e108bb47b7)

**Comment by davidferlay** [comment]
After further test, it looks like there is an issue with permission. It does not seem possible to write any new file in container mounted volume : 

```
➜  launchrctl platform:compare-artifact  -vvv --use-volume-wd
DEBUG: Starting execution of the action "platform:compare-artifact" in "docker" environment, command [sh /action/main.sh  ]
Image "platform-actions-compare-artifact:latest" exists locally
INFO: Image "platform-actions-compare-artifact:latest" exists locally
Flag "--use-volume-wd" is set. Copying the working directory inside the container.
+ ls -lah
+ grep new_file
+ true
+ touch new_file
touch: new_file: Permission denied
DEBUG: [hijack] End of stdout
DEBUG: Error resize: Error response from daemon: container 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc is not running
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
DEBUG: Error resize: Error response from daemon: No such container: 51b7f05380d6d6daec3733dc7c90694c03a73cd71f168f80065a51ff20a83fcc
failed to resize tty, using default size
INFO: action "platform:compare-artifact" finished with the exit code 1
```

**Comment by davidferlay** [comment]
Working as expecte :ok_hand: 

```
➜ docker rmi test:latest; launchrctl platform:test -vvv --use-volume-wd        
rm: cannot remove 'new_file': No such file or directory                                       
Error response from daemon: No such image: test:latest
DEBUG: Starting execution of the action "platform:test" in "docker" environment, command [sh /action/main.sh]
Image "platform-actions-compare-artifact:latest" exists locally
INFO: Image "platform-actions-compare-artifact:latest" exists locally
Flag "--use-volume-wd" is set. Copying the working directory inside the container.
+ rm -rf new_file
+ echo YAY
+ ls -lah
+ grep new_file
-rw-r--r--    1 plasma   plasma         4 Dec  7 10:47 new_file
DEBUG: [hijack] End of stdout
INFO: action "platform:test" finished with the exit code 0
Flag "--use-volume-wd" is set. Copying back the result of the action run.

➜ ls -lah | grep "new_file"
-rw-r--r--  1 dferlay dferlay    4 Dec  7 11:47 new_file
```
