### ISSUE TITLE
"mockgen" Not Found During "make install"

### ISSUE THREAD

**Issue by dhia-gharsallaoui** [launchrctl/launchr#28]
**Description:**

Encountered an error during `make install`: "mockgen" executable not found in $PATH, preventing successful installation.

**Error Details:**
`Error: running "make install" - "mockgen": exec: "mockgen": executable file not found in $PATH`

**Steps to Reproduce:**
1. Execute `make install`.
2. Observe error regarding missing "mockgen" executable.

**Possible Solutions:**
- Add "mockgen" as a requirement in the README with installation instructions.
- Alternatively, update the makefile to install "mockgen" as a dependency during the installation process.

**Comment by lexbritvin** [comment]
Should be fixed
