### ISSUE TITLE
Avoid recursive discovery of actions in `launchrctl --version`

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#35]
## Observed

- Currently, recursive discovery of actions (`**/actions/*/action.yaml`) happens everytime a launchrctl command is executed
- Considering that launchrctl binary may be installed globaly on system, user can execute it from any directory, including system root `/`
- When that happens, command may take a lot of time to complete because of discovery time, which can be very long if disks are not SSD
- That's by design and actually makes sense for most commands
- However command `--version` does not need to discover actions, and can legitimately be run by user anywhere on it's system
- https://github.com/launchrctl/launchr/blob/main/plugins/yamldiscovery/plugin.go#L49
- https://github.com/launchrctl/launchr/blob/main/app.go#L220

## Expected

- `--version` command should not do any discovery

**Comment by davidferlay** [comment]
https://github.com/launchrctl/launchr/pull/38/files

**Comment by davidferlay** [comment]
Merged current state but keeping issue optn as global logic requires some rework

**Comment by DeNevero** [comment]
https://github.com/launchrctl/launchr/pull/39
