### ISSUE TITLE
Action discovery includes hidden directories

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#5]
## Observed

- Launchr discover and list actions that lives in a hidden directory like `.compose` : 

```
➜ ag -g bump-related -a
platform/actions/bump-related/
.compose/build/platform/actions/bump-related/

➜ launchr discover
platform:bump-related
compose.build.platform:bump-related
```

## Expected

- By default, launchr should not list actions defined in hidden direcotries
- An option could be added to `launchr discover` to find actions defined in hidden directories, in case user does need it

**Comment by iignatevich** [comment]
https://github.com/launchrctl/launchr/pull/16
