### ISSUE TITLE
String type is expected for "keyring.GetKeyValue" processor

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/launchr#73]
### Observed
- `plasmactl platform:deploy dev tag --keyring-passphrase X --logs` works
- `plasmactl platform:deploy dev tag --password "XXX" --keyring-passphrase X --logs` does not work anymore

- Passing both options to use new credentials to be used by action and saved in keyring produce an error:
   - `  ERROR   string type is expected for "keyring.GetKeyValue" processor. Change value type or remove the processor` 

### Expected

- Passing both options to use new credentials to be used by action and saved in keyring should not produce any error

### Todo

- Debug

**Comment by lexbritvin** [comment]
Regression after #67
